version: "3.7"

services:
    mysql:
        image: mysql:latest
#        build:
#            context: ./docker/containers/mysql
#            dockerfile: ./Dockerfile
        container_name: ${APP_NAME}_mysql
        ports:
            - ${DB_PORT}:3306
        environment:
#            MYSQL_DATABASE: ${DB_DATABASE}
#            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root
        restart: unless-stopped
        volumes:
            - ./logs/mysql:/var/log/mysql
            - ./docker/data/mysql:/var/lib/mysql
#        network_mode: "host"
        expose:
            -   "3306"
