version: "3.7"

services:
    nginx:
        build:
            context: ./.docker/containers/nginx
            dockerfile: ./Dockerfile
        container_name: ${APP_NAME}_nginx
        ports:
            - "${HTTP_PORT:-80}:80"
        depends_on:
            - php
        volumes:
            - ./:/var/www/html
            - ./.docker/logs/nginx:/var/log/nginx
        links:
            - php
        restart: unless-stopped
        networks:
            default:
                aliases:
                    - site.root
    php:
        build:
            context: ./.docker/containers/php
            dockerfile: ./Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
            - ./.docker/logs/php:/var/logs/php
            - ./.docker/data/sessions:/var/www/html/storage/framework/sessions
        links:
            -   mysql
        restart: unless-stopped
        environment:
            APP_ENV: ${APP_ENV}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: "${DB_HOST:-3306}"
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    mysql:
        build:
            context: ./.docker/containers/mysql
            dockerfile: ./Dockerfile
        container_name: ${APP_NAME}_mysql
        ports:
            - "${DB_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: keys
        restart: unless-stopped
        volumes:
            - ./.docker/logs/mysql:/var/log/mysql
            - ./.docker/data/mysql:/var/lib/mysql
